services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mahatest_mongo:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - mahatest_redis:/data

  nats:
    image: nats:2.10-alpine
    command: ['-js', '-m', '8222']
    ports:
      - '4222:4222'
      - '8222:8222'

volumes:
  mahatest_mongo:
  mahatest_redis:
